import Head from "next/head";
import styles from "@/styles/Home.module.css";
import axios from "axios";

export async function getServerSideProps() {
  const res = await axios.get("http://localhost:8080/hall-of-fame");
  return {
    props: {
      users: res.data.hallOfFame, //should be "ok"
    },
  };
}

interface User {
  ID: number;
  Name: string;
  Tries: number;
  NumToGuess: number;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: string;
}

type Props = {
  users: User[];
};

export default function Home({ users }: Props) {
  const userComponent = users?.map((user: User) => (
    <p key={user.ID}>{user.Name}</p>
  ));

  return (
    <>
      <Head>
        <title>NGUESER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>{userComponent}</div>
      </main>
    </>
  );
}
